"""Shared runtime kernel for all sdlc-ai-spec Phase Skills."""

from .authority import FrozenAuthorityVerificationError
from .authority_compat import (
    FrozenArtifactAuthorityVerifier,
    compute_ctx_check_set_result_digest,
    compute_ctx_control_input_digest,
)
from .canonical import (
    CanonicalFormatError,
    ParsedCanonicalArtifact,
    authority_reference,
    compute_check_set_result_digest,
    compute_control_input_digest,
    exact_artifact_reference,
    parse_canonical_artifact,
    parse_front_matter,
    parse_markdown_tables,
    parse_reference_set,
    sha256_bytes,
)
from .control_inputs import (
    ControlInputError,
    ControlInputResolver,
    RLSIssueControlInput,
    VFYReturnControlInput,
)
from .envelopes import (
    EnvelopeValidationError,
    INVOCATION_CONTRACT,
    OPERATIONS,
    RESULT_CONTRACT,
    error_result,
    validate_invocation,
    validate_result,
)
from .phase import PhaseHandler, execute_phase
from .skill_command import normalize_command_aliases, parse_skill_command
from .skill_args import (
    ArgumentWarning,
    INTERFACE_CONTRACT,
    META_COMMANDS,
    SkillArgumentError,
    SkillCommand,
    SkillInterfaceSpec,
    load_skill_interface,
    parse_skill_arguments,
    render_commands,
    render_examples,
    render_help,
    render_version,
    skill_interface_from_mapping,
)
from .skill_inputs import (
    SkillCommandWithInputs,
    parse_skill_command_with_extensions,
    parse_skill_command_with_inputs,
)
from .source_lock import (
    ContractSource,
    REGISTRY_CONTRACT,
    SOURCE_LOCK_CONTRACT,
    SourceLockError,
    build_source_lock,
    load_registry,
    registry_sources,
    sha256_file,
    validate_source_lock_shape,
    verify_source_lock,
)

__all__ = [
    "ArgumentWarning",
    "CanonicalFormatError",
    "ContractSource",
    "ControlInputError",
    "ControlInputResolver",
    "EnvelopeValidationError",
    "FrozenArtifactAuthorityVerifier",
    "FrozenAuthorityVerificationError",
    "INTERFACE_CONTRACT",
    "INVOCATION_CONTRACT",
    "META_COMMANDS",
    "OPERATIONS",
    "ParsedCanonicalArtifact",
    "PhaseHandler",
    "REGISTRY_CONTRACT",
    "RESULT_CONTRACT",
    "RLSIssueControlInput",
    "SOURCE_LOCK_CONTRACT",
    "SkillArgumentError",
    "SkillCommand",
    "SkillCommandWithInputs",
    "SkillInterfaceSpec",
    "SourceLockError",
    "VFYReturnControlInput",
    "authority_reference",
    "build_source_lock",
    "compute_check_set_result_digest",
    "compute_control_input_digest",
    "compute_ctx_check_set_result_digest",
    "compute_ctx_control_input_digest",
    "error_result",
    "exact_artifact_reference",
    "execute_phase",
    "load_registry",
    "load_skill_interface",
    "parse_canonical_artifact",
    "parse_front_matter",
    "parse_markdown_tables",
    "parse_reference_set",
    "normalize_command_aliases",
    "parse_skill_arguments",
    "parse_skill_command",
    "parse_skill_command_with_inputs",
    "parse_skill_command_with_extensions",
    "registry_sources",
    "render_commands",
    "render_examples",
    "render_help",
    "render_version",
    "sha256_bytes",
    "sha256_file",
    "skill_interface_from_mapping",
    "validate_invocation",
    "validate_result",
    "validate_source_lock_shape",
    "verify_source_lock",
]
